# GitHub Action KeepAlive to post GitHub metrics to an Azure Function App webhook
# GitHub Actions go to sleep after 60 days of no activity
# This action runs every 30 days and updates the .gitclonetimestamp with the current UTC
# This will generate a git check out, update the .gitclonetimestamp, and git commit and push to the repo

name: "GitHub repo metrics report keep alive"

on:
  schedule:
    # Run this once per day, towards the end of the day for keeping the most
    # recent data point most meaningful (hours are interpreted in UTC).
    - cron: "0 23 * * *"
  workflow_dispatch: # Allow for running this manually.

jobs:
    resources:
        name: Update resources
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: timestamp
              run: date -Iseconds -u > .gitclonetimestamp

            - name: Update resources
              run: |
                git add .
                git config user.name "Git Clone Counter"
                git commit -am "Clone Count Report"
                git push
