# GitHub Action Keep Alive to post repo metrics to an Azure Function App webhook
# GitHub Actions go to sleep after 60 days of no activity
# This action runs every month and updates the .gitclonetimestamp with the current UTC
# This will generate a git check out, update the .gitclonetimestamp, and git commit and push to the repo
# This activity will keep the git hub repo metrics action alive

name: "GitHub repo metrics report keep alive"

on:
  schedule:
    # Run this once per day, towards the end of the day for keeping the most
    # recent data point most meaningful (hours are interpreted in UTC).
    # https://cron.help/every-month
    - cron: "15 23 * * *"
  workflow_dispatch: # Allow for running this manually.

jobs:
    resources:
        name: Update the repo metrics timestamp
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: timestamp
              run: date -Iseconds -u > .stats_timestamp

            - name: Update stats timestamp
              run: |
                git add .stats_timestamp
                git config user.name "Repo Stats Timestamp"
                git commit -am "Repo Stats Timestamp"
                git push
